### ISSUE TITLE
detector for orphaned images 

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/wiki#128] opened 2018-09-28 00:01 UTC
**URL of page(s) of concern**
various

**Describe problem**

We have a number of png images in /assets ./assets and /images that are orphaned.  In addition to the dead link detection we should also have orphaned image detection to be able to clean up regularly.

**Comment by vortexing** [comment] 2018-09-28 15:50
Duplicate of issue #125

**Closed by vortexing** 2018-09-28 15:50 UTC
