### ISSUE TITLE
Bionic last deets

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#628] opened 2020-09-17 22:19 UTC
Should this move over to scicompannounce? https://sciwiki.fredhutch.org/compdemos/gizmo-bionic-changelog/
Should this also move/merge with the first bullet in SciCompAnnounce, OR live on as a Bionic-gotcha page?  https://sciwiki.fredhutch.org/compdemos/gizmo-bionic-known_issues/
This strikes me as mostly scicompannounce, with a touch of Bionic-gotchas.  https://sciwiki.fredhutch.org/compdemos/gizmo-bionic-upgrade/

Should this NoMachine + Bionic info also be consolidated into a Bionic Gotcha page?  Or left as is.  I can see it either way https://sciwiki.fredhutch.org/compdemos/gizmo-nx-users/

**Comment by atombaby** [comment] 2023-09-08 17:24
Addressed in PR #840, I think this was mostly a dupe of #769

**Closed by atombaby** 2023-09-08 17:24 UTC
Labels: scientific computing, refresh content
