### ISSUE TITLE
Dream: Little Contributor icons at the bottom of each content page!!

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#434] opened 2019-10-31 21:48 UTC
In a dream world, we could actually use the GitHub API to render at the bottom of each page, the users who have contributed commits to that page. 

This is conceivable given that GitHub itself can do it, but someone would have to take a moment and puzzle this out.  

See how GitHub does it for a single page:

<img width="1057" alt="Screen Shot 2019-10-31 at 2 46 14 PM" src="https://user-images.githubusercontent.com/13182518/67988499-67df0200-fbed-11e9-85a2-1901a31df405.png">

**Comment by bmcgough** [comment] 2019-11-01 16:09
I have never seen this, outside an actual github page, but avatar_url is part of the available user info through the api.

**Comment by dtenenba** [comment] 2023-06-02 17:21
Duplicate of #78

**Closed by dtenenba** 2023-06-02 17:21 UTC
Labels: web-styling
